---
- name: Create grafana data directory
  file: path=/opt/docker/grafana state=directory mode=0755

- name: grafana
  docker:
    name: grafana
    image: grafana/grafana
    state: running
    ports:
      - 3000:3000
    volumes: /opt/docker/grafana/lib:/var/lib/grafana
# Needed to be commented out due to old ansible version:
#    env:
#      GF_USERS_ALLOW_SIGN_UP: false
#      GF_SECURITY_ADMIN_PASSWORD: pingu123
#      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
