logging:
  level: DEBUG
  loggers:
    org: INFO
    com: INFO
    io: INFO
    info: INFO
    no: INFO
    freemarker: INFO
    no.scienta.plantilla: DEBUG
  appenders:
  # Use a file appender for a real application
    - type: console
      logFormat: '%d [%-5p] [%10.10t][%X{app}][%c][%M][%L] - %m%n'

server:
  gzip:
    enabled: false
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 18080
