logging:
  level: DEBUG
  loggers:
    org: INFO
    com: INFO
    io: INFO
    info: INFO
    no: INFO
    freemarker: INFO
    no.scienta.plantilla: DEBUG
  appenders:
    - type: console
      logFormat: '%d [%-5p] %highlight(%-5level) %cyan(%logger{15}) %white(%X{app})[%M][%L] - %m%n'

server:
  gzip:
    enabled: false
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 18080

# See https://github.com/stuartgunter/dropwizard-cassandra/tree/master/src/test/resources
#cassandra:
#  clusterName: "tut"
#  contactPoints: ["localhost", "172.17.0.2", "172.17.0.3", "172.17.0.4"]